name: Publish Docker image

on:
  workflow_call:
    inputs:
      dockerhub_name:
        default: rspamd/bimi-helper
        required: false
        type: string

jobs:
  docker_build:
    runs-on: ["ubuntu-latest"]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set variables
        run: |
          export VERSION_FULL=${{ github.ref_name }}
          export VERSION_MAJOR_MINOR=${VERSION_FULL%.*}
          export VERSION_MAJOR=${VERSION_MAJOR_MINOR%.*}
          echo "IMG_TAGS=ghcr.io/${{ github.repository }}:latest,${{ inputs.dockerhub_name }}:latest,ghcr.io/${{ github.repository }}:${VERSION_FULL},${{ inputs.dockerhub_name }}:${VERSION_FULL},ghcr.io/${{ github.repository }}:${VERSION_MAJOR_MINOR},${{ inputs.dockerhub_name }}:${VERSION_MAJOR_MINOR},ghcr.io/${{ github.repository }}:${VERSION_MAJOR},${{ inputs.dockerhub_name }}:${VERSION_MAJOR}" >> "$GITHUB_ENV"

      - name: Build release image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMG_TAGS }}
